### PR TITLE
Add  my data in the data.JSON file

### PR DESCRIPTION
**Pull request by Elemento24**
# Pull Request 

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #(issue)].

## Types of changes made
- [ ] Fixed Bug
- [ ] Added new Features
- [ ] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Test 1
- Test 2

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [ ] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Review by rush-tea — COMMENTED** [review]
hey @Elemento24 you were supposed to edit only names and links...this has created a merge conflict...

**Comment by Elemento24** [comment]
Hey @rush-tea , when I saved the file, my extensions automatically did the formatting. Is there any way, where I can save them, without having any extensions do any formatting, and also without disabling any of them?

**Comment by rush-tea** [comment]
> Hey @rush-tea , when I saved the file, my extensions automatically did the formatting. Is there any way, where I can save them, without having any extensions do any formatting, and also without disabling any of them?

Hey @Elemento24 I think u can edit it on github only, since you don't have a lot to do..

**Review by Tlazypanda — COMMENTED** [review]
Hey @Elemento24 we might want to remove the merge conflicts here 😅

**Comment by Elemento24** [comment]
Sure @Tlazypanda and @rush-tea, I will do it in Github only!

**Pull request closed without merging**
