### PR TITLE
Added  Footer To The Team And Project Page

### LINKED ISSUE #118: Add footer in team page and project page
# Feature Request
Add footer in team page and project page.

### PR DESCRIPTION
**Pull request by geeks5551**
# Pull Request 

## Proposed Changes
- Added Footer To the Team Page And Project Page With Styling Like Animation, Transition And Hovering Effects.
- Fixes #118 

## Screenshots 
FOOTER1
FOOTER2

## Types of changes made
- Added new Features
- Added Styled Footer to the Team And Project Page as shown Above

### CODE REVIEW

**Comment by geeks5551** [comment]
@deepakDOTexe pls Review

**Review by Tlazypanda — COMMENTED** [review]
Hey @geeks5551 can you align the about us and quick links section in the same row Instead of stacking them?

**Comment by geeks5551** [comment]
okk i am working on it

**Comment by deepakDOTexe** [comment]
@geeks5551 Hey Shivam there are some merge conflicts. Please resolve them asap.

**Pull request closed without merging**
