### PR TITLE
Set up the project structure

### LINKED ISSUE #3: Design framework: Set up a simple boilerplate with the design library of your choice
# Feature Request

### Describe your problem
Set up the project structure with the design library (bulma)

### PR DESCRIPTION
**Pull request by garvitchittora**
# Pull Request 

## Proposed Changes
- fixes #3
- Set up the project structure, linked with Bulma cdn, Google Font (Test), and added a simple header from Bulma components.

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Hey @garvitchittora can you also add a screenshot? Thanks ✌️

**Comment by garvitchittora** [comment]
@Tlazypanda I need to setup react as well?

**Comment by Tlazypanda** [comment]
No @garvitchittora this is fine :sweat_smile:

**Review by Tlazypanda — APPROVED** [review]
@garvitchittora Approved :)

**Comment by Tlazypanda** [comment]
@all-contributors add @garvitchittora  for code

**Pull request merged**
