### PR TITLE
Implement Light and Dark Mode

### LINKED ISSUE #113: Toggle the site from dark to light theme (Part 1) Home Page
# Feature Request

### Describe your problem
Create a light themed equivalent of the current home page by creating the css rules for light theme.
Refer this: -  https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

### PR DESCRIPTION
**Pull request by 2802harsh**
# Pull Request 

## Proposed Changes
- Dark and Light Mode Implemeted
- Initially mode is detected based on user preference,i.e, if user prefers dark mode website opens in dark mode , or if user has light mode preference, website opens in light mode.
- There is also a toggle switch in all pages, so that user can change the dark/light mode.
- LIVE LINK : [here](https://2802harsh.github.io/elevate-lab-website/index.html)
- Fixes #113 #114 #115

## Types of changes made
- [ ] Fixed Bug
- [x] Added new Features
- [ ] Edited Documentations
- [x] Enhanced the working of code
- [ ] Additional Changes

## Screenshots or GIFs (*if any*)
- Screenshot from 2020-10-13 15-53-33
- Screenshot from 2020-10-13 15-53-43
- Screenshot from 2020-10-13 15-54-06
- Screenshot from 2020-10-13 15-55-39

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by hardikbajaj** [comment]
I think #115 assigned to me is also resolved now.

**Comment by 2802harsh** [comment]
oh!! I didn't notice we were assigned the issues in parts

**Comment by deepakDOTexe** [comment]
@2802harsh There are merge conflicts please resolve them and as @hardikbajaj pointed out that this will also close the issue assigned to others, What do you propose now?

**Comment by 2802harsh** [comment]
@deepakDOTexe Sir I think it would be a better option to have common dark and light css files for all pages, otherwise we would then have to open new issues for syncing the light mode styles over various pages.
Further a toggle has also been included that works globally.

**Comment by deepakDOTexe** [comment]
@2802harsh okay then I will merge this PR once u mention the issue numbers which will be fixed in the description of this PR and resolve the merge conflicts.

**Comment by 2802harsh** [comment]
@deepakDOTexe sir please review

**Pull request merged**
