### PR TITLE
Added Contact Us section

### PR DESCRIPTION
**Pull request by Ayush-Baranwal**
# Pull Request 

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #(issue)].

## Types of changes made
- [ ] Fixed Bug
- [ ] Added new Features
- [ ] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Open using Github pages.
link is https://ayush-baranwal.github.io/elevate-lab-website/
- Test 2

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
Screenshot (200)
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by Ayush-Baranwal** [comment]
mam is it ok now.

**Review by Tlazypanda — APPROVED** [review]
Hey @Ayush-Baranwal awesome :fire: Hope you learnt something new and nice to see that you persevered through it!

**Comment by Tlazypanda** [comment]
@all-contributors add @Ayush-Baranwal for code

**Comment by Ayush-Baranwal** [comment]
@Tlazypanda  Mam I have a doubt, For updating my fork repository I deleted it and again fork it and in this process I have to start a new chain.
Is there a way to update the forked repository with deleting it.

**Comment by rush-tea** [comment]
Hey @Ayush-Baranwal you can refer this :- 
Syncing your fork...
using GitHub only i.e. in the browser itself - https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
using Git in your terminal - https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request merged**
