### PR TITLE
added Github Pages Link and updated data.json

### LINKED ISSUE #71: Add site gh pages link to readme
# Feature Request

### Describe your problem
Add the website's gh pages link to readme.

### PR DESCRIPTION
**Pull request by hardikbajaj**
# Pull Request 

## Proposed Changes
- Added the link to Github Pages. FIXES #71 
- Added my details in data.json. 

## Types of changes made
- [ ] Fixed Bug
- [ X] Added new Features
- [ X] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Ran the README.md file locally, working fine

## Checklist:
- [ x] My code follows the Mentioned Guidelines for the project
- [x ] I have self-reviewed the changes made
- [ x] I have made the changes easy to understand by adding comments
- [ x] My changes does not generate new warnings/errors
- [ x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Hey @hardikbajaj can you resolve the merge conflicts here? Rest all looks great 🎉

**Comment by hardikbajaj** [comment]
Resolved!!

**Review by Tlazypanda — APPROVED** [review]
@hardikbajaj approved 💯

**Comment by Tlazypanda** [comment]
@all-contributors add @hardikbajaj for doca

**Comment by Tlazypanda** [comment]
@all-contributors add @hardikbajaj for docs

**Pull request merged**
