### PR TITLE
data read from json file

### LINKED ISSUE #33: Fetch team card data from json
# Feature Request

### Describe your problem

Currently we are adding the cards by repetition Creating a json file and js script to extract data from there and looping it will make the process much simpler.

### PR DESCRIPTION
**Pull request by garvitchittora**
# Pull Request 

## Proposed Changes
- reading data from JSON file
- [line link](https://garvitchittora.github.io/elevate-lab-website/assets/html/team.html)
- fixes #33

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Hey @garvitchittora is this ready for a review? 😅

**Comment by garvitchittora** [comment]
@Tlazypanda yes ma'am. some prob.?

**Comment by Tlazypanda** [comment]
The live link isn't visible it seems that you have deleted your fork 😅

**Comment by garvitchittora** [comment]
@Tlazypanda  yes ma'am.plz see the ss. 

Screenshot (350)

**Review by Tlazypanda — APPROVED** [review]
@garvitchittora changes look great 💯 but so many me's just tells people I am a narcissist 🤦 can we have a generic Avatar Instead please 😇

**Comment by garvitchittora** [comment]
@Tlazypanda ma'am can you plz merge this one since I have deleted my repo :(. I will make changes in JSON and then generate one more PR.

**Comment by Tlazypanda** [comment]
@garvitchittora np :)

**Pull request merged**
