### PR TITLE
Fixed Issues #88, #89 & #112

### PR DESCRIPTION
**Pull request by Priyansh-09**
# Pull Request 

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #(issue)].

## Types of changes made
- [x] Fixed Bug
- [x] Added new Features
- [ ] Edited Documentations
- [x] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Test 1
- Test 2

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [ ] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by Priyansh-09** [comment]
Adding Screenshots to show fixed scrolling feature

Screenshot 2020-10-11 105501
Screenshot 2020-10-11 105740
Screenshot 2020-10-11 105805

**Review by Tlazypanda — COMMENTED** [review]
Hey @Priyansh-09 can you please share the github pages link as well? :sweat_smile: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site This link might help to set it up :v: 

Also in the data.json file it seems that you have removed Jeff and Vishesh's entries by mistake can you correct that too? Thank you! :100:

**Comment by Priyansh-09** [comment]
> 
> 
> Hey @Priyansh-09 can you please share the github pages link as well? 😅 https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site This link might help to set it up ✌️
> 
> Also in the data.json file it seems that you have removed Jeff and Vishesh's entries by mistake can you correct that too? Thank you! 💯

That was added after I created my first PR. So I didn't knew about that. Adding them to this as well

**Comment by Priyansh-09** [comment]
@Tlazypanda Github Pages link - https://priyansh-09.github.io/elevate-lab-website/
Added Jeff and Vishesh to data.json

**Comment by Priyansh-09** [comment]
Added About Us section in footer to solve issue #112 .

Screenshot 2020-10-11 133508

**Comment by Priyansh-09** [comment]
@Tlazypanda please review it once again and merge my PR.

**Review by Tlazypanda — COMMENTED** [review]
Hey @Priyansh-09 no requirement to edit the all-contributors file since that will be done by me using the bot. Also you could have split this pr into 3 prs for the issues solved, could have got your pr count up for hacktoberfest. Are you sure you want to proceed with this? 😅

**Comment by Priyansh-09** [comment]
No Problem with that, I want to proceed with this.

**Review by deepakDOTexe — APPROVED** [review]

**Pull request merged**
