### PR TITLE
Home page connected with links to social media platforms

### PR DESCRIPTION
**Pull request by hardikbajaj**
# Pull Request 

## Proposed Changes
- Social Handle Links connected

## Types of changes made
- Fixed Bug
- [x] Added new Features
- [x] Edited Documentations
- [x] Enhanced the working of code
- [x] Additional Changes
Screenshot from 2020-10-10 23-20-56

### CODE REVIEW

**Comment by tejma17** [comment]
Hello @hardikbajaj, can you make them(links) open in a separate tab?

**Comment by hardikbajaj** [comment]
Yes!! It would be better

**Comment by hardikbajaj** [comment]
## TESTED
Screenshot from 2020-10-11 11-30-51

**Review by tejma17 — APPROVED** [review]
Great @hardikbajaj, approved.

**Comment by Tlazypanda** [comment]
Closing in this ref to discussion

**Pull request closed without merging**
