### PR TITLE
Darkmode Error in Contact Us Fixed

### PR DESCRIPTION
**Pull request by IC1101Virgo**
Rectified the darkmode by changing index.js.
Here is the live link : https://ic1101virgo.github.io/elevate-lab-website/

Please tell me if there are any suggestions 💃 #238

### CODE REVIEW

**Comment by garvitchittora** [comment]
only one issue ig the default dark mode button should be check.

Screenshot (457)_LI

**Comment by IC1101Virgo** [comment]
@garvitchittora Its working fine in my live link  https://ic1101virgo.github.io/elevate-lab-website/ . 
Actually in the current website if you click on contact us and then use dark mode you can't use it. So that seems fixed.
Please let me know if I am missing something.

**Comment by garvitchittora** [comment]
> only one issue ig the default dark mode button should be check.
> 
> Screenshot (457)_LI

this error is still there with your link also, open in incognito 🤷.

**Comment by dastgirp** [comment]
Isn't this duplicate of #252 ?

**Comment by IC1101Virgo** [comment]
@garvitchittora I'll check it out. @dastgirp Do you want to work on this issue?

**Comment by IC1101Virgo** [comment]
@garvitchittora I have made some changes please review. I opened this in incognito mode too it seems to be working even the button.
Let me know. 
Thanks 😄

**Pull request closed without merging**
