### PR TITLE
Added Navbar Responsiveness

### LINKED ISSUE #99: Navbar:Make It More Responsive
make navbar more responsive by adding  animated hovering effect and transitions

### PR DESCRIPTION
**Pull request by geeks5551**
# Pull Request 

## Proposed Changes
- Added  Animations and Transitions effects to the Navbar at the same time fixing it(navbar) upon scrolling
-  Fixes #99.

ResponsiveNav
ResponsiveNav2
ResponsiveNav3

## Types of changes made
-  Added new Features to the style.css File inside Assets/css Folder and index.html file (To Fix the Navbar Upon Scrolling In Bulma Framework), Rest All Files/Folders Are Unchanged.
- Additional Changes Made  As Mentioned and Shown Above.

### CODE REVIEW

**Comment by geeks5551** [comment]
Plz Review Above PR And Issue

**Comment by Priyansh-09** [comment]
Thus issue is the combination of issue assigned to me (fix navbar scrolling) and issue assigned to @garvitchittora (adding hover effects on navbar items). So this issue that you have opened is conflicting those two issues that was assigned to us.

**Review by Tlazypanda — COMMENTED** [review]
Hey @geeks5551 seems like you have made a copy of all the files and added here so total 14 files are being changed :sweat_smile: can you please check this? Thank you! :v:

**Comment by geeks5551** [comment]
Ma'am actually I have modified codes in only two files namely index.html and style.css rest all files are the same /unchanged

**Pull request closed without merging**
