### PR TITLE
Fixes dark mode not applicable when clicked on contactUs or learn link

### LINKED ISSUE #238: Dark Mode Toggle not working for Contact Section
# Bug Report 

### Issue Summary

    Dark Mode Toggle Button not working if we go to Contact Section (On clicking 'Contact' Navbar). You may go through the ss attached

### Expected Behaviour
 
Page should remain in Mode(dark/light) even after clicking Contact Navbar Link

### Screenshots (if any)

Screenshot from 2020-10-22 20-17-03

### PR DESCRIPTION
**Pull request by dastgirp**
Fixes #238

# Pull Request 

## Proposed Changes
- Changed location.href to location.pathname, as pathname reads only the file name and disregards query parameters

## Types of changes made
- [x] Fixed Bug
- [ ] Added new Features
- [ ] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- NA

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Review by Tlazypanda — COMMENTED** [review]
Hey @dastgirp can you add a screenshot or gif for these changes? Thank you! :tada:

**Comment by dastgirp** [comment]
@Tlazypanda 
image

**Comment by dastgirp** [comment]
Any update?

**Comment by dastgirp** [comment]
@deepakDOTexe @Tlazypanda

**Comment by dastgirp** [comment]
@tejma17 @IC1101Virgo any updates?

**Comment by IC1101Virgo** [comment]
@dastgirp heya! I would like you to take look at a possible bug which might be there. If you put dark mode on after clicking on ContactUs and then open it in incognito or new window the toggle button gives an error. 
Check it out once. 😄 
Also, it would be great if you could provide a live link.
Thanks 😺

**Comment by IC1101Virgo** [comment]
@Tlazypanda @deepakDOTexe @tejma17 please merge this pull request it does the job for now. I have reviewed it.
Thanks!

**Pull request merged**
