### PR TITLE
Added Name and Useful Resources

### PR DESCRIPTION
**Pull request by kumarmanish03**
#7 

##Added my name and useful resources for technical learning

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [ ] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [ ] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Review by Tlazypanda — COMMENTED** [review]
Hey @kumarmanish03 you have removed a '}' at the end in data.json file 😅

**Comment by kumarmanish03** [comment]
@Tlazypanda please review

**Review by Tlazypanda — COMMENTED** [review]
Hey @kumarmanish03 some names have been accidentally removed from the data.json file 😅 kindly verify

**Comment by kumarmanish03** [comment]
Issues solved #7 and #40

**Review by Tlazypanda — APPROVED** [review]
@kumarmanish03 approved 🔥

**Comment by Tlazypanda** [comment]
@all-contributors add @kumarmanish03 for docs

**Pull request merged**
