### PR TITLE
Issue 117 fetch project card data from json

### PR DESCRIPTION
**Pull request by Thilagavathi1**
# Pull Request 

## Proposed Changes
- Fetched project card data from json. 
- [Fixes #(117)].

## Types of changes made
- [ ] Enhanced the working of code

### CODE REVIEW

**Comment by Thilagavathi1** [comment]
@garvitchittora @Tlazypanda Please check this PR and merge it.

**Comment by garvitchittora** [comment]
@Thilagavathi1 please resolve the conflict and we want 3 project cards in one row right, so this will not work for your code means all cards will be visible in one row only in place of 3 cards in each row as per your code (for reference please check team.js).

**Comment by Thilagavathi1** [comment]
ProjectsPage
@garvitchittora Resolved the merge conflicts.please check the screenshots for the projects page.

**Comment by garvitchittora** [comment]
> @Thilagavathi1 we want 3 project cards in one row right, so this will not work for your code means all cards will be visible in one row only in place of 3 cards in each row as per your code (for reference please check team.js).

I think you have not resolved the row issue, plz solve that part.

**Comment by Thilagavathi1** [comment]
> > @Thilagavathi1 we want 3 project cards in one row right, so this will not work for your code means all cards will be visible in one row only in place of 3 cards in each row as per your code (for reference please check team.js).
> 
> I think you have not resolved the row issue, plz solve that part.
i have displayed how it was displayed previousely.whats is your expected design for the projects screen.Please check the screenshots i was shared previous comment

**Comment by garvitchittora** [comment]
Hi @Thilagavathi1, this is your result (I have cloned your repo.), now please see in this ss in one row 4 cards are there but we need 3 in one row.

 
Screenshot (380)

**Comment by Thilagavathi1** [comment]
> Hi @Thilagavathi1, this is your result (I have cloned your repo.), now please see in this ss in one row 4 cards are there but we need 3 in one row.
> 
> Screenshot (380)

Got it now. let me rework on it

**Comment by Thilagavathi1** [comment]
@garvitchittora have made the changes as per your requirements.Please check this and let me know the feedback.

**Review by garvitchittora — APPROVED** [review]

**Pull request merged**
