### PR TITLE
Added Footer With Social Media Plugins

### PR DESCRIPTION
**Pull request by uglyprincess**
# Pull Request 

## Proposed Changes
- Added a footer containing links to social media plugins. 

## Types of changes made
- [x ] Added new Features

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
New Project (4)
 | 
New Project (3)

## Checklist:
- [x ] My code follows the Mentioned Guidelines for the project
- [x ] I have self-reviewed the changes made
- [x ] I have made the changes easy to understand by adding comments
- [ x] My changes does not generate new warnings/errors
- [ x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by uglyprincess** [comment]
@Tlazypanda could you please review this PR? 😅😅😬

**Review by Tlazypanda — COMMENTED** [review]
Hey @uglyprincess can you remove the How to contribute.txt file from the files changed

**Comment by uglyprincess** [comment]
> Hey @uglyprincess can you remove the How to contribute.txt file from the files changed

done ma'am 👍🏻

**Comment by Tlazypanda** [comment]
Hey @uglyprincess one last change since I missed it the last time can you keep the handles empty except the GitHub one since we are not associating this with dsc yet as we want contributors to contribute from anywhere. Associating this with DSC might make it limited to our campus. Thank you!

**Comment by uglyprincess** [comment]
> Hey @uglyprincess one last change since I missed it the last time can you keep the handles empty except the GitHub one since we are not associating this with dsc yet as we want contributors to contribute from anywhere. Associating this with DSC might make it limited to our campus. Thank you!

Good call, handles removed!

**Review by Tlazypanda — APPROVED** [review]
@uglyprincess Awesome 👏 Thank you 💯

**Pull request merged**
