### PR TITLE
added event page

### LINKED ISSUE #102: Design Event section and cards
# Feature Request

### Describe your problem

Design the event section and cards. The event section should have the heading "Event".

### PR DESCRIPTION
**Pull request by garvitchittora**
# Pull Request 

## Proposed Changes
- added event page
- Fixes #102 

- SS
Screenshot (372)

## Checklist:
- [X] My code follows the Mentioned Guidelines for the project
- [X] I have self-reviewed the changes made
- [X] I have made the changes easy to understand by adding comments
- [X] My changes does not generate new warnings/errors
- [X] I have attached relevant screenshots to display the changes made
- [X] I have made the required changes to the documentations

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Tlazypanda @deepakDOTexe @tejma17 plz review :)

**Comment by tejma17** [comment]
Hello @garvitchittora, Past Events section is looking a bit compressed 😅. Also, I don't think we need to specify the venue for past events. Can you improve the design accordingly?
Moreover, Past events will stack up as we proceed further. Consider it while designing.

**Comment by garvitchittora** [comment]
for stack up, we can use pagination for that.

**Comment by tejma17** [comment]
Yeah. Just improve past events cards.

**Comment by garvitchittora** [comment]
after changes @tejma17 

Screenshot (377)

**Comment by tejma17** [comment]
@garvitchittora one more suggestion 😅. It would be better if the date and View Event button are in the same row.

**Comment by garvitchittora** [comment]
@tejma17 

Screenshot (379)

**Review by tejma17 — APPROVED** [review]

**Pull request merged**
