### PR TITLE
Fixed issues #88 (fix navbar scrolling) and #89 (add reference links to logo and brand text) on all pages

### PR DESCRIPTION
**Pull request by Priyansh-09**
# Pull Request 

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #(issue)].

## Types of changes made
- [x] Fixed Bug
- [x] Added new Features
- [ ] Edited Documentations
- [x] Enhanced the working of code
- [ ] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Test 1
- Test 2

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [ ] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by Priyansh-09** [comment]
Adding Screenshots to show the fixed navbar scrolling
Screenshot 2020-10-11 105501
Screenshot 2020-10-11 105740
Screenshot 2020-10-11 105805

**Comment by tejma17** [comment]
Hi @Priyansh-09 we might want to resolve the merge conflicts here.

**Comment by Priyansh-09** [comment]
I have resolved it.

**Review by tejma17 — APPROVED** [review]
@Priyansh-09 Approved 🙌

**Review by Tlazypanda — COMMENTED** [review]
Hey @Priyansh-09 Looks like you have made a copy of the files and are adding all the files again :sweat_smile: since 15 files are changed here

**Comment by Priyansh-09** [comment]
@Tlazypanda I'm this PR and creating a new one that fixes this

**Pull request closed without merging**
